listaNova = {
    "0": {"nome":"Outro", "controlado":False, "altaVigilancia":False},
    "996":{"nome":"Acetazolamida 250mg cp","controlado":False,"altaVigilancia":False},
"2186":{"nome":"Aciclovir Creme 10g","controlado":False,"altaVigilancia":False},
"2190":{"nome":"Aciclovir 200mg cp","controlado":False,"altaVigilancia":False},
"2188":{"nome":"Aciclovir 250mg ev inj","controlado":False,"altaVigilancia":False},
"7181":{"nome":"Ácido Acetilsalicílico Tamponado 100mg cp","controlado":False,"altaVigilancia":False},
"204":{"nome":"Ácido Acetilsalicílico 100mg cp","controlado":False,"altaVigilancia":False},
"1416":{"nome":"Ácido Fólico 5mg cp","controlado":False,"altaVigilancia":False},
"36590":{"nome":"Ácido Folínico 300mg inj","controlado":False,"altaVigilancia":False},
"36591":{"nome":"Ácido Folínico 50mg inj","controlado":False,"altaVigilancia":False},
"11060":{"nome":"Ácido Folínico 15mg cp","controlado":False,"altaVigilancia":False},
"36639":{"nome":"Ácido Tranexâmico 250mg cp","controlado":False,"altaVigilancia":False},
"826":{"nome":"Ácido Tranexâmico 50mg/ml 5ml inj","controlado":False,"altaVigilancia":False},
"37205":{"nome":"Ácido Ursodesoxicólico 50mg cp","controlado":False,"altaVigilancia":False},
"37123":{"nome":"Ácido Valpróico 250mg cap","controlado":True,"altaVigilancia":False},
"1291":{"nome":"Ácido Valpróico 50mg/ml Sol Oral (Frasco C/100ml)","controlado":True,"altaVigilancia":False},
"11561":{"nome":"Ácido Valpróico 500mg drg","controlado":True,"altaVigilancia":False},
"539":{"nome":"Adenosina 3mg/ml 2ml inj","controlado":False,"altaVigilancia":False},
"1582":{"nome":"Adrenalina 1mg/ml 1ml inj","controlado":False,"altaVigilancia":True},
"193":{"nome":"Água Destilada 10ml inj","controlado":False,"altaVigilancia":False},
"41713":{"nome":"Água Destilada 1000ml Sistema Fechado inj","controlado":False,"altaVigilancia":False},
"195":{"nome":"Água Destilada 20ml inj","controlado":False,"altaVigilancia":False},
"10080":{"nome":"Albendazol 400mg cp","controlado":False,"altaVigilancia":False},
"1577":{"nome":"Albumina Humana 20% 50ml inj","controlado":False,"altaVigilancia":False},
"57518":{"nome":"Álcool Absoluto (99%) 10ml inj","controlado":False,"altaVigilancia":False},
"6250":{"nome":"Alfentanila 0,5mg/ml 5ml inj","controlado":True,"altaVigilancia":False},
"804":{"nome":"Alopurinol 100mg cp","controlado":False,"altaVigilancia":False},
"806":{"nome":"Alopurinol 300mg cp","controlado":False,"altaVigilancia":False},
"37034":{"nome":"Alprazolam 0,25mg cp","controlado":True,"altaVigilancia":False},
"1403":{"nome":"Alprazolam 1,0mg cp","controlado":True,"altaVigilancia":False},
"38871":{"nome":"Alprostadil 20mcg 2ml inj","controlado":False,"altaVigilancia":True},
"7911":{"nome":"Alteplase 50mg inj.","controlado":False,"altaVigilancia":False},
"7024":{"nome":"Amantadina 100mg cp","controlado":True,"altaVigilancia":False},
"712":{"nome":"Amicacina Sulfato 250mg/ml 2ml inj","controlado":False,"altaVigilancia":False},
"708":{"nome":"Amicacina Sulfato 50mg/ml 2ml inj","controlado":False,"altaVigilancia":False},
"1006":{"nome":"Amilorida 5mg + Hidroclorotiazida 50mg cp","controlado":False,"altaVigilancia":False},
"2320":{"nome":"Aminofilina 24mg/ml inj 10ml","controlado":False,"altaVigilancia":False},
"541":{"nome":"Amiodarona 200mg cp","controlado":False,"altaVigilancia":False},
"3081":{"nome":"Amiodarona 50mg/ml inj 3ml","controlado":False,"altaVigilancia":False},
"1654":{"nome":"Amitriptilina 25mg cp","controlado":True,"altaVigilancia":False},
"586":{"nome":"Amoxicilina 500mg cp","controlado":False,"altaVigilancia":False},
"96987":{"nome":"Amoxicilina 875mg + Clavulanato 125mg cp","controlado":False,"altaVigilancia":False},
"749":{"nome":"Ampicilina 1g + Sulbactam 0,5g inj","controlado":False,"altaVigilancia":False},
"588":{"nome":"Ampicilina 1g inj ev","controlado":False,"altaVigilancia":False},
"11941":{"nome":"Ampicilina 2G + Sulbactam 1g inj","controlado":False,"altaVigilancia":False},
"602":{"nome":"Ampicilina 500mg cp","controlado":False,"altaVigilancia":False},
"590":{"nome":"Ampicilina 500mg inj ev","controlado":False,"altaVigilancia":False},
"643":{"nome":"Anfotericina B Desoxicolato 50mg inj","controlado":False,"altaVigilancia":False},
"36553":{"nome":"Anfotericina B Lipossomal 50mg inj","controlado":False,"altaVigilancia":False},
"2212":{"nome":"Anlodipina Besilato 10mg cp","controlado":False,"altaVigilancia":False},
"36654":{"nome":"Anlodipina Besilato 5mg cp","controlado":False,"altaVigilancia":False},
"96087":{"nome":"Apixabana 2,5mg cp rev","controlado":False,"altaVigilancia":False},
"79071":{"nome":"Apixabana 5mg cp rev","controlado":False,"altaVigilancia":False},
"18101":{"nome":"Atenolol 25mg cp","controlado":False,"altaVigilancia":False},
"9100":{"nome":"Atenolol 50mg cp","controlado":False,"altaVigilancia":False},
"37255":{"nome":"Atorvastatina 10mg cp","controlado":False,"altaVigilancia":False},
"40005":{"nome":"Atorvastatina 40mg cp","controlado":False,"altaVigilancia":False},
"457":{"nome":"Atracúrio Besilato 10mg/ml 2,5ml inj","controlado":False,"altaVigilancia":False},
"564":{"nome":"Atropina Sulfato 0,25mg/ml inj","controlado":False,"altaVigilancia":False},
"1465":{"nome":"Atropina Sulfato 0,5% Colírio 5ml","controlado":False,"altaVigilancia":False},
"36982":{"nome":"Azatioprina 50mg cp","controlado":False,"altaVigilancia":False},
"12702":{"nome":"Azitromicina 500mg cp","controlado":False,"altaVigilancia":False},
"24971":{"nome":"Azitromicina 500mg inj","controlado":False,"altaVigilancia":False},
"592":{"nome":"Aztreonam 1g inj","controlado":False,"altaVigilancia":False},
"41672":{"nome":"Azul De Metileno 2% 5ml (Estéril)","controlado":False,"altaVigilancia":False},
"12145":{"nome":"Azul Patente 2,5% (Ampola C/ 2ml)","controlado":False,"altaVigilancia":False},
"8865":{"nome":"Baclofeno 10mg cp","controlado":False,"altaVigilancia":False},
"57387":{"nome":"Baclofeno 2000mcg/ml 20ml inj","controlado":False,"altaVigilancia":False},
"132104":{"nome":"Baclofeno 4mg/ml 20ml inj.","controlado":False,"altaVigilancia":False},
"6470":{"nome":"Bamifilina 300mg drg","controlado":False,"altaVigilancia":False},
"38035":{"nome":"Bariogel - Sulfato De Bário 1g/ml 150ml","controlado":False,"altaVigilancia":False},
"39851":{"nome":"Beclometasona Dipropionato Aquoso Nasal 50mcg spray","controlado":False,"altaVigilancia":False},
"3253":{"nome":"Beclometasona Dipropionato 250mcg/Dosespray oral","controlado":False,"altaVigilancia":False},
"11390":{"nome":"Beclometasona Dipropionato 400mcg/ml 2ml flaconete","controlado":False,"altaVigilancia":False},
"38955":{"nome":"Beclometasona Dipropionato 50mcg/Dose spray oral","controlado":False,"altaVigilancia":False},
"7203":{"nome":"Benzidamida Colutório 150ml fr","controlado":False,"altaVigilancia":False},
"596":{"nome":"Benzilpenicilina Benzatina 1.200.000 Ui/4ml inj","controlado":False,"altaVigilancia":False},
"57480":{"nome":"Benzocaína 45mg/G+Triclosana 5mg/G+Mentol 5mg/g 43g aerossol","controlado":False,"altaVigilancia":False},
"38913":{"nome":"Betaistina Dicloridrato 24mg cp","controlado":False,"altaVigilancia":False},
"40088":{"nome":"Betaistina Dicloridrato 8mg cp","controlado":False,"altaVigilancia":False},
"18106":{"nome":"Betametasona + Cetoconazol Tubo 30g","controlado":False,"altaVigilancia":False},
"872":{"nome":"Betametasona Dipropionato 5mg/ml","controlado":False,"altaVigilancia":False},
"Betametasona Fosfato Dissódico 2":{"nome":"Betametasona Fosfato Dissódico 2mg/ml 1ml inj","controlado":False,"altaVigilancia":False},
"3517":{"nome":"Betametasona (Fosfato Dissódico + Acetato) 6mg/ml 1ml inj","controlado":False,"altaVigilancia":False},
"39721":{"nome":"Betametasona Fosfato Dissódico 4mg inj","controlado":False,"altaVigilancia":False},
"39053":{"nome":"Betametasona Valerato 1mg/g creme 30g","controlado":False,"altaVigilancia":False},
"1587":{"nome":"Bicarbonato De Sódio pó 1g sache","controlado":False,"altaVigilancia":False},
"186":{"nome":"Bicarbonato De Sódio 8,4% 10ml inj","controlado":False,"altaVigilancia":False},
"103755":{"nome":"Bicarbonato De Sódio 8,4% 250ml inj","controlado":False,"altaVigilancia":False},
"1240":{"nome":"Biperideno 2mg cp","controlado":True,"altaVigilancia":False},
"1247":{"nome":"Biperideno 5mg/ml 1ml inj","controlado":True,"altaVigilancia":False},
"1228":{"nome":"Bisacodil 5mg drg","controlado":False,"altaVigilancia":False},
"37236":{"nome":"Bisoprolol 1,25mg cp","controlado":False,"altaVigilancia":False},
"1502":{"nome":"Bromazepam 3mg cp","controlado":True,"altaVigilancia":False},
"57408":{"nome":"Brometo De Ipratróprio 0,02mg/Jato + Bromidrato De Fenoterol 0,05mg/Jato Aerosol 10ml","controlado":False,"altaVigilancia":False},
"36940":{"nome":"Bromexina Expectorante 1,6mg/ml Xarope 120ml","controlado":False,"altaVigilancia":False},
"494":{"nome":"Bromoprida 10mg cap","controlado":False,"altaVigilancia":False},
"496":{"nome":"Bromoprida 4mg/ml Gts 20ml","controlado":False,"altaVigilancia":False},
"493":{"nome":"Bromoprida 5mg/ml inj 2ml","controlado":False,"altaVigilancia":False},
"443":{"nome":"Bupivacaína 0,5 % C/ Epinefrina 20ml inj","controlado":False,"altaVigilancia":True},
"441":{"nome":"Bupivacaína 0,5 % S/ Vasoconstritor 20ml inj","controlado":False,"altaVigilancia":True},
"445":{"nome":"Bupivacaína Isobárica 0,5 % 4ml inj","controlado":False,"altaVigilancia":True},
"36130":{"nome":"Bupivacaína Pesada 0,5 % 4ml inj. Embalagem Estéril.","controlado":False,"altaVigilancia":True},
"36128":{"nome":"Bupivacaína 0,25% S/Vasoconstritor 20ml inj","controlado":False,"altaVigilancia":True},
"439":{"nome":"Bupivacaína 0,75% S/ Epinefrina 20ml","controlado":False,"altaVigilancia":True},
"39808":{"nome":"Bupropiona Cloridrato 150mg cp","controlado":True,"altaVigilancia":False},
"41496":{"nome":"Cabergolina 0,5mg cp","controlado":False,"altaVigilancia":False},
"68870":{"nome":"Cafeína Citrato 20mg/ml 1ml- Vo/ Ev","controlado":False,"altaVigilancia":False},
"10340":{"nome":"Calcitriol 0,25mcg cap","controlado":False,"altaVigilancia":False},
"849":{"nome":"Captopril 25mg cp","controlado":False,"altaVigilancia":False},
"1641":{"nome":"Carbamazepina 20mg/ml Susp Oral 100ml","controlado":False,"altaVigilancia":False},
"1633":{"nome":"Carbamazepina 200mg cp","controlado":True,"altaVigilancia":False},
"1637":{"nome":"Carbamazepina 400mg cp","controlado":True,"altaVigilancia":False},
"1625":{"nome":"Carbidopa 25mg + Levodopa 250mg cp","controlado":False,"altaVigilancia":False},
"2270":{"nome":"Carbonato De Cálcio 500mg cp","controlado":False,"altaVigilancia":False},
"1288":{"nome":"Carbonato De Lítio 300mg cp","controlado":False,"altaVigilancia":False},
"36848":{"nome":"Cartucho Tca I-Stat Kaolin Act Cartrige (Tempo Coagulacao Ativa)","controlado":False,"altaVigilancia":False},
"2354":{"nome":"Carvão Ativado 60G","controlado":False,"altaVigilancia":False},
"58367":{"nome":"Carvedilol 12,5mg cp","controlado":False,"altaVigilancia":False},
"6400":{"nome":"Carvedilol 3,125mg cp","controlado":False,"altaVigilancia":False},
"36995":{"nome":"Cássia (6mg Senosídeos) + Senna cap","controlado":False,"altaVigilancia":False},
"102803":{"nome":"Cateter Externo Masculino (Uripen) N°05","controlado":False,"altaVigilancia":False},
"103562":{"nome":"Cavilon Creme Tubo 92G","controlado":False,"altaVigilancia":False},
"68155":{"nome":"Cavilon Spray Protetor Cutâneo 28ml","controlado":False,"altaVigilancia":False},
"36264":{"nome":"Cefadroxil 500mg cp","controlado":False,"altaVigilancia":False},
"665":{"nome":"Cefalexina Monoidratada 500mg drg","controlado":False,"altaVigilancia":False},
"669":{"nome":"Cefalexina 50mg/ml Susp Oral Fr 100ml","controlado":False,"altaVigilancia":False},
"657":{"nome":"Cefazolina 1G inj","controlado":False,"altaVigilancia":False},
"673":{"nome":"Cefepime 1G inj","controlado":False,"altaVigilancia":False},
"7761":{"nome":"Cefepime 2G Ev inj","controlado":False,"altaVigilancia":False},
"699":{"nome":"Cefoxitina Sódica 1G inj","controlado":False,"altaVigilancia":False},
"637":{"nome":"Ceftazidima 1G inj","controlado":False,"altaVigilancia":False},
"104612":{"nome":"Ceftazidima 2G + Avibactam 500mg inj","controlado":False,"altaVigilancia":False},
"737":{"nome":"Ceftriaxona 1G inj","controlado":False,"altaVigilancia":False},
"37112":{"nome":"Cefuroxima Axetil 500mg cp","controlado":False,"altaVigilancia":False},
"757":{"nome":"Cefuroxima Sódica 750mg Ev inj","controlado":False,"altaVigilancia":False},
"39718":{"nome":"Celecoxibe 200mg cp","controlado":True,"altaVigilancia":False},
"36560":{"nome":"Cetoconazol 2% Creme 30G","controlado":False,"altaVigilancia":False},
"36563":{"nome":"Cetoconazol 2% Xampu","controlado":False,"altaVigilancia":False},
"27584":{"nome":"Cetoprofeno Enterico 100mg cp","controlado":False,"altaVigilancia":False},
"2371":{"nome":"Cetoprofeno 100mg Ev inj","controlado":False,"altaVigilancia":False},
"39732":{"nome":"Cetoprofeno 50mg cap","controlado":False,"altaVigilancia":False},
"55436":{"nome":"Cetrimida + Ol. Amêndoas Doce + Ol Calêndula pomada 40G","controlado":False,"altaVigilancia":False},
"39764":{"nome":"Ciclobenzaprina Cloridrato 5mg cp","controlado":False,"altaVigilancia":False},
"40801":{"nome":"Cilostazol 50mg cp","controlado":False,"altaVigilancia":False},
"528":{"nome":"Cimetidina 150mg/ml inj 2ml","controlado":False,"altaVigilancia":False},
"20931":{"nome":"Ciprofibrato 100mg cp","controlado":False,"altaVigilancia":False},
"34211":{"nome":"Ciprofloxacino 0,3% + Dexametasona 0,1% pomada Oftálmica 3,5G","controlado":False,"altaVigilancia":False},
"18104":{"nome":"Ciprofloxacino 0,35% Colírio 5ml","controlado":False,"altaVigilancia":False},
"19401":{"nome":"Ciprofloxacino 2mg/ml 200ml inj","controlado":False,"altaVigilancia":False},
"722":{"nome":"Ciprofloxacino 500mg cp","controlado":False,"altaVigilancia":False},
"26048":{"nome":"Citalopram 20mg cp","controlado":True,"altaVigilancia":False},
"1421":{"nome":"Claritromicina 500mg Ev inj","controlado":False,"altaVigilancia":False},
"3511":{"nome":"Clindamicina Cloridrato 300mg caps","controlado":False,"altaVigilancia":False},
"613":{"nome":"Clindamicina Fosfato 150mg/ml 4ml inj","controlado":False,"altaVigilancia":False},
"1398":{"nome":"Clobazam 10mg cp","controlado":True,"altaVigilancia":False},
"1286":{"nome":"Clomipramina 25mg","controlado":True,"altaVigilancia":False},
"37029":{"nome":"Clonazepam Sl 0,25mg cp","controlado":True,"altaVigilancia":False},
"1619":{"nome":"Clonazepam 0,5mg cp","controlado":True,"altaVigilancia":False},
"1621":{"nome":"Clonazepam 2mg cp","controlado":True,"altaVigilancia":False},
"9221":{"nome":"Clonazepam 2.5mg/ml Gotas 20ml","controlado":True,"altaVigilancia":False},
"4802":{"nome":"Clonidina 0,100mg cp","controlado":False,"altaVigilancia":False},
"18092":{"nome":"Clonidina 0,150mg cp","controlado":False,"altaVigilancia":False},
"10640":{"nome":"Clonidina 150mcg/ml 1ml inj","controlado":False,"altaVigilancia":False},
"16961":{"nome":"Clopidogrel 75mg cp","controlado":False,"altaVigilancia":False},
"26981":{"nome":"Cloreto De Sódio 0,9% Nacl10ml inj","controlado":False,"altaVigilancia":False},
"36734":{"nome":"Cloreto De Sódio 20% 10ml inj","controlado":False,"altaVigilancia":True},
"37081":{"nome":"Cloreto De Sódio 20% 20ml inj","controlado":False,"altaVigilancia":True},
"131900":{"nome":"Cloridrato De Lidocaína 2%/20mg/ml 20ml inj - S/ Vasoconstritor - Frasco-Ampola - Aps","controlado":False,"altaVigilancia":False},
"2266":{"nome":"Cloridrato De Nafazolina 0,5mg/ml (Contém Benzalcônio + Nacl 0,9%) - Solução Nasal / Fr 30ml","controlado":False,"altaVigilancia":False},
"1258":{"nome":"Clorpromazina 100mg cp","controlado":True,"altaVigilancia":False},
"1279":{"nome":"Clorpromazina 25mg cp","controlado":True,"altaVigilancia":False},
"1269":{"nome":"Clorpromazina 40mg/ml Gts 20ml","controlado":True,"altaVigilancia":False},
"1274":{"nome":"Clorpromazina 5mg/ml inj 5ml","controlado":True,"altaVigilancia":False},
"36966":{"nome":"Clortalidona 25mg cp","controlado":False,"altaVigilancia":False},
"28971":{"nome":"Clotrimazol 1% Creme (Tubo C/20G)","controlado":False,"altaVigilancia":False},
"11850":{"nome":"Clozapina 25mg cp","controlado":True,"altaVigilancia":False},
"37116":{"nome":"Codeína 30mg cp","controlado":True,"altaVigilancia":False},
"37117":{"nome":"Codeína 30mg/ml inj 2ml","controlado":True,"altaVigilancia":False},
"39055":{"nome":"Colagenase + Cloranfenicol pomada 30G","controlado":False,"altaVigilancia":False},
"802":{"nome":"Colchicina 0,5mg cp","controlado":False,"altaVigilancia":False},
"133342":{"nome":"Colecalciferol (Vitamina D3) 14.000 Ui/ml - 10ml","controlado":False,"altaVigilancia":False},
"3322":{"nome":"Colestiramina Pó 4G","controlado":False,"altaVigilancia":False},
"930":{"nome":"Complexo B drg","controlado":False,"altaVigilancia":False},
"201":{"nome":"Complexo B 2ml inj","controlado":False,"altaVigilancia":False},
"51952":{"nome":"Complexo Protrombinico Concentrado 500 Ui inj","controlado":False,"altaVigilancia":False},
"66858":{"nome":"Compressa Operatória 25 X 28Cm 18G Estéril Com Fio Radiopaco","controlado":False,"altaVigilancia":False},
"40265":{"nome":"Curativo Antibacteriano Com Prata 10 X 10Cm","controlado":False,"altaVigilancia":False},
"36138":{"nome":"Curativo De Alginato De Cálcio 9,5 X 19Cm","controlado":False,"altaVigilancia":False},
"54145":{"nome":"Curativo Transp. Opsite Iv 3000 9X12M","controlado":False,"altaVigilancia":False},
"95607":{"nome":"Dabigatrana 150mg cap","controlado":False,"altaVigilancia":True},
"11513":{"nome":"Dantroleno Sódico 20mg inj","controlado":True,"altaVigilancia":False},
"107504":{"nome":"Dapagliflozina 10mg cp Rev","controlado":False,"altaVigilancia":False},
"83201":{"nome":"Daptomicina 500mg inj","controlado":False,"altaVigilancia":False},
"135148":{"nome":"Deferasirox 500mg cp","controlado":False,"altaVigilancia":False},
"2209":{"nome":"Deslanosideo 0,2mg/ml 2ml inj","controlado":False,"altaVigilancia":False},
"53420":{"nome":"Desmopressina Acetato 0,1mg/ml Spray Nasal 2,5ml","controlado":False,"altaVigilancia":False},
"36976":{"nome":"Desmopressina Acetato 4mcg/ml 1ml inj","controlado":False,"altaVigilancia":False},
"166":{"nome":"Dexametasona Fosfato Dissódico 4mg/ml 2,5ml inj","controlado":False,"altaVigilancia":False},
"37125":{"nome":"Dexametasona 0,1% Creme 10G","controlado":False,"altaVigilancia":False},
"1457":{"nome":"Dexametasona 1,0mg/ml + Neomicina 5,0mg/ml + Polimixina B 6.000 Ui/ml Suspensão Oftálmica 5ml","controlado":False,"altaVigilancia":False},
"2237":{"nome":"Dexametasona 4mg cp","controlado":False,"altaVigilancia":False},
"882":{"nome":"Dexclorfeniramina Maleato 2mg cp","controlado":False,"altaVigilancia":False},
"39126":{"nome":"Dexclorfeniramina 0,4mg/ml + Betametasona 0,05mg/ml Xarope 120ml","controlado":False,"altaVigilancia":False},
"22061":{"nome":"Dexmedetomidina 100mcg/ml 2ml inj","controlado":False,"altaVigilancia":False},
"30411":{"nome":"Dexpantenol 50mg Creme 30G","controlado":False,"altaVigilancia":False},
"4961":{"nome":"Dextrana 1mg/ml + Hipromelose 3mg/ml 15ml Sol. Oft.","controlado":False,"altaVigilancia":False},
"39789":{"nome":"Dextrocetamina Cloridrato 50mg/ml 10ml inj","controlado":False,"altaVigilancia":False},
"39788":{"nome":"Dextrocetamina Cloridrato 50mg/ml 2ml inj","controlado":False,"altaVigilancia":False},
"1295":{"nome":"Diazepam 10mg cp","controlado":True,"altaVigilancia":False},
"1293":{"nome":"Diazepam 5mg cp","controlado":True,"altaVigilancia":False},
"1656":{"nome":"Diazepam 5mg/ml 2ml inj","controlado":True,"altaVigilancia":False},
"11070":{"nome":"Diclofenaco Dietilamonio Emulgel 11,6mg/G Gel Dermatológico Bisnaga - 60G","controlado":False,"altaVigilancia":False},
"2182":{"nome":"Diclofenaco Sódico 25mg/ml 3ml inj","controlado":False,"altaVigilancia":False},
"2180":{"nome":"Diclofenaco Sódico 50mg cp","controlado":False,"altaVigilancia":False},
"19461":{"nome":"Difenidramina 50mg/ml 1ml inj","controlado":False,"altaVigilancia":False},
"2219":{"nome":"Digoxina 0,25mg cp","controlado":False,"altaVigilancia":False},
"7273":{"nome":"Diltiazem Sr 90mg cp","controlado":False,"altaVigilancia":False},
"851":{"nome":"Diltiazem 30mg cp","controlado":False,"altaVigilancia":False},
"504":{"nome":"Dimenidrinato 25mg/ml + Piridoxina 5mg/ml Gts 20ml","controlado":False,"altaVigilancia":False},
"502":{"nome":"Dimenidrinato 30mg + Vitamina B6 +Glicose + D-Frutose 10ml inj","controlado":False,"altaVigilancia":False},
"500":{"nome":"Dimenidrinato 50mg + Piridoxina 10mg cp Rev","controlado":False,"altaVigilancia":False},
"2304":{"nome":"Diosmina 450mg + Hesperidina 50mg cp","controlado":False,"altaVigilancia":False},
"58498":{"nome":"Dipiridamol 5mg/ml 2ml inj","controlado":False,"altaVigilancia":False},
"310":{"nome":"Dipirona + Prometazina + Adifenina Gts 15ml","controlado":False,"altaVigilancia":False},
"348":{"nome":"Dipirona Sódica 500mg cp","controlado":False,"altaVigilancia":False},
"344":{"nome":"Dipirona Sódica 500mg/ml Gts 20ml","controlado":False,"altaVigilancia":False},
"342":{"nome":"Dipirona Sódica 500mg/ml 2ml inj","controlado":False,"altaVigilancia":False},
"2224":{"nome":"Dobutamina 12,5mg/ml 20ml inj","controlado":False,"altaVigilancia":True},
"11511":{"nome":"Domperidona 1mg/ml Susp 100ml","controlado":False,"altaVigilancia":False},
"3766":{"nome":"Domperidona 10mg cp","controlado":False,"altaVigilancia":False},
"67457":{"nome":"Donepezila Cloridrato 5mg cp.","controlado":False,"altaVigilancia":False},
"1585":{"nome":"Dopamina 5mg/ml 10ml inj","controlado":False,"altaVigilancia":True},
"18118":{"nome":"Doxazosina 2mg cp","controlado":False,"altaVigilancia":False},
"755":{"nome":"Doxiciclina Monoidratada 100mg drg","controlado":False,"altaVigilancia":False},
"25233":{"nome":"Droperidol 2,5mg/ml 1ml inj","controlado":True,"altaVigilancia":False},
"71458":{"nome":"Duloxetina Cloridrato 30mg cp","controlado":True,"altaVigilancia":False},
"1451":{"nome":"Efedrina 50mg/ml 1ml inj","controlado":False,"altaVigilancia":True},
"859":{"nome":"Enalapril Maleato 10mg cp","controlado":False,"altaVigilancia":False},
"863":{"nome":"Enalapril Maleato 5mg cp","controlado":False,"altaVigilancia":False},
"761":{"nome":"Enoxaparina 20mg/0,2ml inj","controlado":False,"altaVigilancia":False},
"11231":{"nome":"Enoxaparina 40mg/0,4ml inj","controlado":False,"altaVigilancia":False},
"23314":{"nome":"Enoxaparina 60mg/0,6ml inj","controlado":False,"altaVigilancia":False},
"23321":{"nome":"Enoxaparina 80mg/0,8ml inj","controlado":False,"altaVigilancia":False},
"133137":{"nome":"Eritromicina 0,5% 3,5G Gel Oftálmico","controlado":False,"altaVigilancia":False},
"133122":{"nome":"Eritromicina 0,5% 5G Pomada Oftálmica","controlado":False,"altaVigilancia":False},
"5546":{"nome":"Eritropoetina Humana Recombinante 4.000 Ui inj","controlado":False,"altaVigilancia":True},
"133945":{"nome":"Eritropoetina Humana Recombinante 40.000 Ui inj. Seringa Preenchida","controlado":False,"altaVigilancia":True},
"23041":{"nome":"Ertapenem Sódico 1G inj","controlado":False,"altaVigilancia":True},
"128033":{"nome":"Escetamina Cloridrato 50mg/ml 2ml inj","controlado":True,"altaVigilancia":False},
"39807":{"nome":"Escitalopram 10mg cp","controlado":True,"altaVigilancia":False},
"14620":{"nome":"Escopolamina Brometo Gts 20ml","controlado":False,"altaVigilancia":False},
"212":{"nome":"Escopolamina Brometo 20mg/ml inj 1ml","controlado":False,"altaVigilancia":False},
"18347":{"nome":"Escopolamina Brometo 6,67mg/ml + Dipirona 337,4mg/ml Gts 20ml","controlado":False,"altaVigilancia":False},
"274":{"nome":"Escopolamina Brometo10mg drg","controlado":False,"altaVigilancia":False},
"268":{"nome":"Escopolamina 4mg/ml + Dipirona 500mg/ml inj 5ml","controlado":False,"altaVigilancia":False},
"272":{"nome":"Escopolamina10mg + Dipirona 250mg cp Rev","controlado":False,"altaVigilancia":False},
"20012":{"nome":"Esmolol 250mg/ml 10ml inj","controlado":False,"altaVigilancia":False},
"25724":{"nome":"Esomeprazol 20mg cp.","controlado":False,"altaVigilancia":False},
"53549":{"nome":"Espacador C/Camara P/Administracao Broncodilatador - Ace","controlado":False,"altaVigilancia":False},
"37244":{"nome":"Espironolactona 1mg/1ml Sol Oral 50ml","controlado":False,"altaVigilancia":False},
"990":{"nome":"Espironolactona 100mg cp","controlado":False,"altaVigilancia":False},
"992":{"nome":"Espironolactona 25mg cp","controlado":False,"altaVigilancia":False},
"1591":{"nome":"Etilefrina 10mg/ml 1ml inj","controlado":False,"altaVigilancia":True},
"431":{"nome":"Etomidato 2mg/ml 10ml inj","controlado":False,"altaVigilancia":False},
"36466":{"nome":"Fenazopiridina 100mg drg","controlado":False,"altaVigilancia":False},
"133938":{"nome":"Fenilefrina 10mg/ml inj 1ml","controlado":False,"altaVigilancia":True},
"52051":{"nome":"Fenilefrina 2,5% + Tropicamida 0,5% Colírio 5ml","controlado":False,"altaVigilancia":False},
"1492":{"nome":"Fenitoína 100mg cp","controlado":True,"altaVigilancia":False},
"1496":{"nome":"Fenitoína 50mg/ml 5ml inj","controlado":True,"altaVigilancia":False},
"1406":{"nome":"Fenobarbital 100mg cp","controlado":True,"altaVigilancia":False},
"1394":{"nome":"Fenobarbital 100mg/ml 2ml inj","controlado":True,"altaVigilancia":False},
"1477":{"nome":"Fenobarbital 40mg/ml Gts 20ml","controlado":True,"altaVigilancia":False},
"8820":{"nome":"Fenoterol Bromidrato 5mg/ml 20ml Gts","controlado":False,"altaVigilancia":False},
"298":{"nome":"Fentanila Citrato 50mcg/ml 2ml inj","controlado":False,"altaVigilancia":False},
"300":{"nome":"Fentanila Citrato 50mcg/ml 10ml inj","controlado":False,"altaVigilancia":False},
"39776":{"nome":"Fentanila Citrato 50mcg/ml 5ml inj","controlado":False,"altaVigilancia":False},
"18170":{"nome":"Fentanila Transdermico 25mcg/H Adesivo","controlado":False,"altaVigilancia":False},
"58652":{"nome":"Ferro Glicinato (Eq. Fe 50mg/ml) + Ácido Fólico Gts (Frasco C/30ml)","controlado":False,"altaVigilancia":False},
"39681":{"nome":"Ferro Quelato Glicinato 500mg cp","controlado":False,"altaVigilancia":False},
"11530":{"nome":"Fexofenadina 60mg cp","controlado":False,"altaVigilancia":False},
"99718":{"nome":"Fibrinogenio Humano Reconstituido Concentrado 1G","controlado":False,"altaVigilancia":False},
"73559":{"nome":"Filgrastima 300mcg/0,5ml inj Seringa","controlado":False,"altaVigilancia":False},
"36980":{"nome":"Finasterida 5mg cp","controlado":False,"altaVigilancia":False},
"915":{"nome":"Fitomenadiona Ev 10mg/ml 1ml inj","controlado":False,"altaVigilancia":False},
"37211":{"nome":"Fitomenadiona Im 10mg/ml 1ml inj","controlado":False,"altaVigilancia":False},
"36571":{"nome":"Fluconazol 150mg cap","controlado":False,"altaVigilancia":False},
"759":{"nome":"Fluconazol 2mg/ml 100ml inj","controlado":False,"altaVigilancia":False},
"4150":{"nome":"Fludrocortisona Acetato 0,1mg cp","controlado":False,"altaVigilancia":False},
"1550":{"nome":"Fludroxicortida Creme 30G","controlado":False,"altaVigilancia":False},
"1500":{"nome":"Flumazenil 0,1mg/ml 5ml inj","controlado":True,"altaVigilancia":False},
"1623":{"nome":"Flunitrazepam 1mg cp","controlado":True,"altaVigilancia":False},
"56234":{"nome":"Fluocortolona1mg + Lidocaina 20mg Creme 30G","controlado":False,"altaVigilancia":False},
"4317":{"nome":"Fluoxetina 20mg cap","controlado":True,"altaVigilancia":False},
"52272":{"nome":"Formoterol Fumarato 12mcg + Budesonida 400mcg 60cp C/ Inalador","controlado":False,"altaVigilancia":False},
"185":{"nome":"Fosfato De Potássio 2Meq/ml 10ml inj","controlado":False,"altaVigilancia":True},
"1230":{"nome":"Fosfato De Sódio Monobasico + Fosfato De Sódio Dibasico Sol. Retal 130ml","controlado":False,"altaVigilancia":False},
"72617":{"nome":"Fosfomicina De Trometamol 5,631G/8G Sache","controlado":False,"altaVigilancia":False},
"18060":{"nome":"Fralda Descartavel Adulto Tamanho Gg","controlado":False,"altaVigilancia":False},
"5020":{"nome":"Furosemida 1mg/ml Sol Oral (Frasco C/ 50ml)","controlado":False,"altaVigilancia":False},
"1002":{"nome":"Furosemida 10mg/ml 2ml inj","controlado":False,"altaVigilancia":False},
"1004":{"nome":"Furosemida 40mg cp","controlado":False,"altaVigilancia":False},
"37031":{"nome":"Gabapentina 300mg cap","controlado":True,"altaVigilancia":False},
"18651":{"nome":"Gabapentina 400mg cap","controlado":True,"altaVigilancia":False},
"123302":{"nome":"Gadoteridol 279,3mg/ml (0,5M) - 10ml","controlado":False,"altaVigilancia":False},
"123305":{"nome":"Gadoteridol 279,3mg/ml (0,5M) - 15ml","controlado":False,"altaVigilancia":False},
"120845":{"nome":"Gadoteridol 279,3mg/ml (0,5M) - 50ml","controlado":False,"altaVigilancia":False},
"55517":{"nome":"Gaze De Rayon C/ Óleo Dermoprotetor Pielsana 7,5 X7,5 C/3ml","controlado":False,"altaVigilancia":False},
"39893":{"nome":"Gelatina Fluida Modificada 500ml inj","controlado":False,"altaVigilancia":False},
"647":{"nome":"Gentamicina 40mg 1ml inj","controlado":False,"altaVigilancia":False},
"651":{"nome":"Gentamicina 80mg/2ml inj","controlado":False,"altaVigilancia":False},
"782":{"nome":"Glibenclamida 5mg cp","controlado":False,"altaVigilancia":False},
"40086":{"nome":"Glicerofosfato De Sódio 216mg/ml (Fosfato 1,0 Mmol/ml/Sódio 2,0 Mmol/ml) 20ml inj","controlado":False,"altaVigilancia":False},
"36744":{"nome":"Glicina Solução 1,5% 3000ml inj","controlado":False,"altaVigilancia":False},
"188":{"nome":"Glicose 25% Hipertônica 10ml inj","controlado":False,"altaVigilancia":True},
"1603":{"nome":"Glicose 50% Hipertônica 10ml inj","controlado":False,"altaVigilancia":True},
"37084":{"nome":"Glicose 50% Hipertônica 20ml inj","controlado":False,"altaVigilancia":True},
"77685":{"nome":"Glicose 75% Hipertônica 10ml inj","controlado":False,"altaVigilancia":True},
"40474":{"nome":"Glimepirida 1mg cp","controlado":False,"altaVigilancia":False},
"8621":{"nome":"Glimepirida 2mg cp","controlado":False,"altaVigilancia":False},
"189":{"nome":"Gluconato De Cálcio 10% 10ml inj","controlado":False,"altaVigilancia":True},
"26722":{"nome":"Granisetrona 1mg/ml 3ml inj","controlado":False,"altaVigilancia":False},
"1481":{"nome":"Haloperidol 1mg cp","controlado":True,"altaVigilancia":False},
"68304":{"nome":"Haloperidol 2mg/ml Gts 20ml","controlado":True,"altaVigilancia":False},
"1487":{"nome":"Haloperidol 5mg cp","controlado":True,"altaVigilancia":False},
"1485":{"nome":"Haloperidol 5mg/ml 1ml inj","controlado":True,"altaVigilancia":False},
"407":{"nome":"Heparina Sódica Subcutânea 5000 Ui/0,25ml inj","controlado":False,"altaVigilancia":False},
"40660":{"nome":"Heparina 5.000 Ui/ml 5ml inj (Endovenosa)","controlado":False,"altaVigilancia":True},
"111992":{"nome":"Hexafluoreto De Enxofre 8 µl/ml","controlado":False,"altaVigilancia":False},
"8723":{"nome":"Hexamidina + Tetracaina Colutório 50ml","controlado":False,"altaVigilancia":False},
"28332":{"nome":"Hidralazina 20/ml 1ml inj","controlado":False,"altaVigilancia":False},
"4114":{"nome":"Hidralazina 25mg drg","controlado":False,"altaVigilancia":False},
"838":{"nome":"Hidralazina 50mg drg","controlado":False,"altaVigilancia":False},
"42145":{"nome":"Hidroclorotiazida 1mg/1ml Solução Oral 50ml","controlado":False,"altaVigilancia":False},
"36967":{"nome":"Hidroclorotiazida 25mg cp","controlado":False,"altaVigilancia":False},
"23628":{"nome":"Hidrocoloide + Alginato De Cálcio E Sódio Gel 85G","controlado":False,"altaVigilancia":False},
"39052":{"nome":"Hidrocortisona Acetato 1% Creme 30G","controlado":False,"altaVigilancia":False},
"71025":{"nome":"Hidrocortisona 10mg/Neomicina 5mg/Polimixina B 10.000 Ui/ml Sol. Otológica 10ml","controlado":False,"altaVigilancia":False},
"2246":{"nome":"Hidrocortisona 100mg inj","controlado":False,"altaVigilancia":False},
"2247":{"nome":"Hidrocortisona 500mg inj","controlado":False,"altaVigilancia":False},
"39137":{"nome":"Hidroxicloroquina Sulfato 400mg cp","controlado":False,"altaVigilancia":False},
"18344":{"nome":"Hidróxido De Alumínio + Magnésio + Dimeticona Fr 240ml Susp Oral","controlado":False,"altaVigilancia":False},
"4270":{"nome":"Hidróxido De Alumínio Fr 240ml Susp Oral","controlado":False,"altaVigilancia":False},
"905":{"nome":"Hidróxido De Ferro 20mg/ml 5ml Ev inj","controlado":False,"altaVigilancia":False},
"6751":{"nome":"Hidroxiureia 500mg cap","controlado":False,"altaVigilancia":False},
"40028":{"nome":"Hidroxizina Cloridrato 2mg/ml Xpe 120ml","controlado":False,"altaVigilancia":False},
"45554":{"nome":"Histoacryl 0,5ml","controlado":False,"altaVigilancia":False},
"36028":{"nome":"Ibuprofeno 50mg/ml Gts 30ml","controlado":False,"altaVigilancia":False},
"1693":{"nome":"Ibuprofeno 600mg cp","controlado":False,"altaVigilancia":False},
"99976":{"nome":"Idarucizumabe 50mg/ml 50ml inj","controlado":False,"altaVigilancia":False},
"1647":{"nome":"Imipramina 25mg drg","controlado":True,"altaVigilancia":False},
"40021":{"nome":"Imunoglobulina Humana Anti-D (Anti-Rho) 1500 Ui/2ml (300mcg) inj.","controlado":False,"altaVigilancia":True},
"40095":{"nome":"Indapamida Sr 1,5mg cp","controlado":False,"altaVigilancia":False},
"11476":{"nome":"Indapamida 2,5mg cp","controlado":False,"altaVigilancia":False},
"82462":{"nome":"Indocianina Verde Ophthalmos (Icv) 25mg 10ml","controlado":False,"altaVigilancia":False},
"53535":{"nome":"Insulina Glargina 100Ui/ml 10ml","controlado":False,"altaVigilancia":True},
"36971":{"nome":"Insulina Humana Nph 100 Ui/ml 10ml inj","controlado":False,"altaVigilancia":True},
"790":{"nome":"Insulina Humana Regular 100Ui/ml 10ml inj","controlado":False,"altaVigilancia":True},
"56699":{"nome":"Insulina Lispro 100Ui/ml 10ml inj","controlado":False,"altaVigilancia":True},
"120846":{"nome":"Iomeprol 400 (816,5mg/ml) - 100ml","controlado":False,"altaVigilancia":False},
"124099":{"nome":"Iomeprol 400 (816,5mg/ml) - 50ml","controlado":False,"altaVigilancia":False},
"126749":{"nome":"Iomeprol 400 (816,5mg/ml) - 500ml*","controlado":False,"altaVigilancia":False},
"134906":{"nome":"Iopamiron - Iopamidol 300 (612,4mg/ml) - 50ml","controlado":False,"altaVigilancia":False},
"13":{"nome":"Iopamiron - Iopamidol 300 (612,4mg/ml) - 50ml","controlado":False,"altaVigilancia":False},
"8822":{"nome":"Ipratróprio Brometo 0,25mg/ml Gts 20ml","controlado":False,"altaVigilancia":False},
"7821":{"nome":"Isoprenalina 0,2mg/ml 1ml inj","controlado":False,"altaVigilancia":False},
"1711":{"nome":"Isossorbida Dinitrato Sl 5mg cp","controlado":False,"altaVigilancia":False},
"1710":{"nome":"Isossorbida Dinitrato 10mg cp","controlado":False,"altaVigilancia":False},
"1716":{"nome":"Isossorbida Mononitrato 10mg/ml 1ml inj","controlado":False,"altaVigilancia":False},
"1719":{"nome":"Isossorbida Mononitrato 20mg cp","controlado":False,"altaVigilancia":False},
"3369":{"nome":"Itraconazol 100mg cap","controlado":False,"altaVigilancia":False},
"18751":{"nome":"Ivermectina 6mg cp","controlado":False,"altaVigilancia":False},
"71557":{"nome":"Lactulose 667mg/ml 15ml Sache","controlado":False,"altaVigilancia":False},
"117382":{"nome":"Lamivudina 10mg/ml - 240ml Solução Oral","controlado":False,"altaVigilancia":False},
"39804":{"nome":"Lamotrigina 25mg cp","controlado":True,"altaVigilancia":False},
"96169":{"nome":"Levetiracetam 100mg/ml Fr 150ml","controlado":True,"altaVigilancia":False},
"39816":{"nome":"Levodopa 100mg + Benserazida 25mg cap Lib Prolongada (Hbs)","controlado":False,"altaVigilancia":False},
"37023":{"nome":"Levodopa 200mg + Benserazida 50mg cp","controlado":False,"altaVigilancia":False},
"53786":{"nome":"Levodropropizina 6mg/ml Xarope 120ml","controlado":False,"altaVigilancia":False},
"36474":{"nome":"Levofloxacino 5mg/ml 100ml inj.","controlado":False,"altaVigilancia":False},
"40148":{"nome":"Levofloxacino 500mg cp","controlado":False,"altaVigilancia":False},
"1529":{"nome":"Levomepromazina 25mg cp","controlado":True,"altaVigilancia":False},
"1525":{"nome":"Levomepromazina 40mg/ml Gts 20ml","controlado":True,"altaVigilancia":False},
"2400":{"nome":"Levotiroxina Sódica 100mcg cp","controlado":False,"altaVigilancia":False},
"7791":{"nome":"Levotiroxina Sódica 25mcg cp","controlado":False,"altaVigilancia":False},
"54606":{"nome":"Levotiroxina Sódica 88mcg","controlado":False,"altaVigilancia":False},
"132791":{"nome":"Liberador Adesivo 50ml Spray","controlado":False,"altaVigilancia":False},
"29131":{"nome":"Lidocaina + Prilocaina 5G Creme","controlado":False,"altaVigilancia":False},
"467":{"nome":"Lidocaina 2% S/ Vasoconstritor 20ml inj","controlado":False,"altaVigilancia":True},
"39802":{"nome":"Lidocaina Pesada 5% 2ml inj","controlado":False,"altaVigilancia":True},
"18080":{"nome":"Lidocaina 10% 50ml Spray","controlado":False,"altaVigilancia":False},
"465":{"nome":"Lidocaina 2 % C/ Epinefrina 20ml inj","controlado":False,"altaVigilancia":True},
"40889":{"nome":"Lidocaina 2% Geleia Estéril (Seringa C/10G)","controlado":False,"altaVigilancia":False},
"471":{"nome":"Lidocaina 2% 30G Tubo","controlado":False,"altaVigilancia":False},
"62462":{"nome":"Linagliptina 5mg cp","controlado":True,"altaVigilancia":False},
"20081":{"nome":"Linezolida 2mg/ml 300ml inj","controlado":False,"altaVigilancia":False},
"127126":{"nome":"Loção Hidratante Com Vitamina A + E Fr 200ml","controlado":False,"altaVigilancia":False},
"29201":{"nome":"Loção Hidratante Rn 200ml","controlado":False,"altaVigilancia":False},
"40864":{"nome":"Loção Lanette C / Mentol + Canfora (Frasco C/100ml)","controlado":False,"altaVigilancia":False},
"36954":{"nome":"Loção Lanette (Frasco C/100ml)","controlado":False,"altaVigilancia":False},
"799":{"nome":"Loperamida Cloridrato 2mg cp","controlado":False,"altaVigilancia":False},
"4504":{"nome":"Loratadina 10mg cp","controlado":False,"altaVigilancia":False},
"37260":{"nome":"Losartana Potássica 25mg cp","controlado":False,"altaVigilancia":False},
"4938":{"nome":"Losartana Potássica 50mg cp","controlado":False,"altaVigilancia":False},
"37148":{"nome":"Lugol 2% (Frasco C/500ml)","controlado":False,"altaVigilancia":False},
"39835":{"nome":"Macrogol + Associacoes 14G Sache","controlado":False,"altaVigilancia":False},
"96988":{"nome":"Magnesio 130mg + Piridoxina 1mg cp","controlado":False,"altaVigilancia":False},
"313":{"nome":"Manitol Solução 20% 250ml","controlado":False,"altaVigilancia":False},
"37243":{"nome":"Memantina Cloridrato 10mg cp","controlado":True,"altaVigilancia":False},
"36477":{"nome":"Meropenem 1G inj","controlado":False,"altaVigilancia":False},
"705":{"nome":"Meropenem 500mg inj","controlado":False,"altaVigilancia":False},
"1223":{"nome":"Mesalazina 400mg cp","controlado":False,"altaVigilancia":False},
"110516":{"nome":"Mesilato De Di-Hidroergotamina 1mg + Dipirona Sódica 350mg + Cafeína 100mg (Cefaliv)","controlado":False,"altaVigilancia":False},
"26697":{"nome":"Mesna 400mg inj","controlado":False,"altaVigilancia":False},
"37151":{"nome":"Metadona 10mg cp","controlado":True,"altaVigilancia":False},
"40493":{"nome":"Metadona 10mg/ml 1ml inj.","controlado":True,"altaVigilancia":False},
"31273":{"nome":"Metadona 5mg cp","controlado":True,"altaVigilancia":False},
"840":{"nome":"Metaraminol Hemitartarato 10mg/ml 1ml inj","controlado":False,"altaVigilancia":False},
"5545":{"nome":"Metformina 500mg cp","controlado":False,"altaVigilancia":False},
"98249":{"nome":"Metformina 500mg cp Lib. Prolongada","controlado":False,"altaVigilancia":False},
"6200":{"nome":"Metformina 850mg cp","controlado":False,"altaVigilancia":False},
"834":{"nome":"Metildopa 250mg cp","controlado":False,"altaVigilancia":False},
"836":{"nome":"Metildopa 500mg cp","controlado":False,"altaVigilancia":False},
"774":{"nome":"Metilergometrina Maleato 0,2mg/ml 1ml inj","controlado":False,"altaVigilancia":False},
"38410":{"nome":"Metilfenidato 10mg cp","controlado":True,"altaVigilancia":False},
"2252":{"nome":"Metilprednisolona Succinato 125mg inj","controlado":False,"altaVigilancia":False},
"2254":{"nome":"Metilprednisolona Succinato 500mg inj","controlado":False,"altaVigilancia":False},
"53519":{"nome":"Metilprednisolona Acetato 40mg/ml 2ml inj","controlado":False,"altaVigilancia":False},
"526":{"nome":"Metoclopramida 10mg cp","controlado":False,"altaVigilancia":False},
"520":{"nome":"Metoclopramida 4mg/ml Gts 10ml","controlado":False,"altaVigilancia":False},
"524":{"nome":"Metoclopramida 5mg/ml 2ml inj","controlado":False,"altaVigilancia":False},
"73567":{"nome":"Metoprolol Succinato 25mg cp","controlado":False,"altaVigilancia":False},
"6261":{"nome":"Metoprolol Tartarato 1mg/ml 5ml inj","controlado":False,"altaVigilancia":False},
"18278":{"nome":"Metoprolol Tartarato 100mg cp","controlado":False,"altaVigilancia":False},
"30321":{"nome":"Metotrexato 25mg/ml 2ml inj.","controlado":False,"altaVigilancia":False},
"40652":{"nome":"Metotrexato 5G inj.","controlado":False,"altaVigilancia":False},
"631":{"nome":"Metronidazol + Nistatina Creme Vaginal 50G","controlado":False,"altaVigilancia":False},
"706":{"nome":"Metronidazol 0,5% 5mg/ml 100ml inj","controlado":False,"altaVigilancia":False},
"627":{"nome":"Metronidazol 250mg cp","controlado":False,"altaVigilancia":False},
"57667":{"nome":"Micafungina Sódica 50mg inj","controlado":False,"altaVigilancia":False},
"18700":{"nome":"Miconazol Nitrato Creme Ginecologico 80G","controlado":False,"altaVigilancia":False},
"1313":{"nome":"Midazolam 1mg/ml 5ml inj","controlado":True,"altaVigilancia":False},
"1311":{"nome":"Midazolam 15mg cp","controlado":True,"altaVigilancia":False},
"11833":{"nome":"Midazolam 5mg/ml 10ml inj","controlado":True,"altaVigilancia":False},
"1309":{"nome":"Midazolam 5mg/ml 3ml inj","controlado":True,"altaVigilancia":False},
"57452":{"nome":"Milrinona Lactato 1mg/ml 10ml inj","controlado":False,"altaVigilancia":False},
"39814":{"nome":"Mirtazapina 15mg cp","controlado":True,"altaVigilancia":False},
"39138":{"nome":"Misoprostol 200mcg cp","controlado":True,"altaVigilancia":False},
"39139":{"nome":"Misoprostol 25mcg cp","controlado":True,"altaVigilancia":False},
"17470":{"nome":"Morfina Sulfato 0,2mg/ml 1ml inj","controlado":True,"altaVigilancia":False},
"1297":{"nome":"Morfina Sulfato 1mg/ml 2ml inj","controlado":True,"altaVigilancia":False},
"6430":{"nome":"Morfina Sulfato 10mg cp","controlado":True,"altaVigilancia":False},
"39985":{"nome":"Morfina Sulfato 10mg/ml 1ml inj","controlado":True,"altaVigilancia":False},
"52288":{"nome":"Mucopolissacarideo Polissulfato 5mg/G Gel (Tubo C/40G)","controlado":False,"altaVigilancia":False},
"28952":{"nome":"Mupirocina 15G pomada","controlado":False,"altaVigilancia":False},
"27262":{"nome":"N-Acetilcisteina 10% 3ml inj","controlado":False,"altaVigilancia":False},
"9071":{"nome":"N-Acetilcisteina 600mg Env","controlado":False,"altaVigilancia":False},
"1535":{"nome":"Nalbufina Cloridrato 10mg/ml 1ml inj","controlado":True,"altaVigilancia":False},
"3557":{"nome":"Naloxona 0,4mg/ml 1ml inj","controlado":True,"altaVigilancia":False},
"7921":{"nome":"Nandrolona 50mg/ml 1ml inj","controlado":False,"altaVigilancia":False},
"29101":{"nome":"Neomicina + Bacitracina pomada 15G","controlado":False,"altaVigilancia":False},
"1583":{"nome":"Neostigmina 0,5mg/ml 1ml inj","controlado":False,"altaVigilancia":False},
"119860":{"nome":"Nestogeno 1 Lata 400 Gramas ( Ministerio Da Saúde)","controlado":False,"altaVigilancia":False},
"39135":{"nome":"Nicotina 21mg Adesivo","controlado":False,"altaVigilancia":False},
"828":{"nome":"Nifedipino 10mg cp","controlado":False,"altaVigilancia":False},
"37179":{"nome":"Nimesulida 100mg cp","controlado":False,"altaVigilancia":False},
"1726":{"nome":"Nimodipino 30mg cp","controlado":False,"altaVigilancia":False},
"29032":{"nome":"Nistatina + Óxido De Zinco Uso Tópico pomada 60G","controlado":False,"altaVigilancia":False},
"1691":{"nome":"Nistatina 100.000 Ui/ml 50ml Susp Oral","controlado":False,"altaVigilancia":False},
"96292":{"nome":"Nitrato De Prata 1% 5ml Colírio","controlado":False,"altaVigilancia":False},
"37154":{"nome":"Nitrato De Prata 5% Bastão","controlado":False,"altaVigilancia":False},
"24993":{"nome":"Nitrendipino 10mg cp.","controlado":False,"altaVigilancia":False},
"18141":{"nome":"Nitrofurantoina 100mg cp","controlado":False,"altaVigilancia":False},
"4240":{"nome":"Nitroglicerina 5mg/ml 10ml inj","controlado":False,"altaVigilancia":True},
"857":{"nome":"Nitroprussiato De Sódio 25mg/ml 2ml inj","controlado":False,"altaVigilancia":True},
"1434":{"nome":"Noradrenalina Hemitartarato 2mg/ml 4ml inj","controlado":False,"altaVigilancia":True},
"397":{"nome":"Norfloxacino 400mg cp","controlado":False,"altaVigilancia":False},
"1613":{"nome":"Nortriptilina Cloridrato 25mg cap","controlado":True,"altaVigilancia":False},
"75993":{"nome":"Npt Olimel N9 1000ml","controlado":False,"altaVigilancia":False},
"3504":{"nome":"Ocitocina 5 Ui/ml 1ml inj","controlado":False,"altaVigilancia":False},
"3528":{"nome":"Octreotida 0,1mg/ml 1ml inj","controlado":False,"altaVigilancia":False},
"37022":{"nome":"Olanzapina 5mg cp","controlado":True,"altaVigilancia":False},
"2203":{"nome":"Óleo Mineral 100ml Fr","controlado":False,"altaVigilancia":False},
"97416":{"nome":"Omeprazol Magnesico 20mg cp","controlado":False,"altaVigilancia":False},
"14191":{"nome":"Omeprazol Sódico 20mg cp","controlado":False,"altaVigilancia":False},
"25722":{"nome":"Omeprazol 40mg inj","controlado":False,"altaVigilancia":False},
"56460":{"nome":"Omnipaque - Ioexol 647mg/ml (300mg I/ml) 50ml","controlado":False,"altaVigilancia":False},
"36607":{"nome":"Ondansetrona Cloridrato 2mg/ml 2ml inj","controlado":False,"altaVigilancia":False},
"312":{"nome":"Ondansetrona Cloridrato 2mg/ml 4ml inj","controlado":False,"altaVigilancia":False},
"18117":{"nome":"Ondansetrona 4mg cp","controlado":False,"altaVigilancia":False},
"36602":{"nome":"Ondansetrona 8mg cp","controlado":False,"altaVigilancia":False},
"24891":{"nome":"Optiray - Ioversol (320mg I/ml) 50ml","controlado":False,"altaVigilancia":False},
"79138":{"nome":"Oseltamivir 75mg cap","controlado":False,"altaVigilancia":False},
"743":{"nome":"Oxacilina 500mg inj","controlado":False,"altaVigilancia":False},
"37202":{"nome":"Oxcarbazepina 300mg cp","controlado":True,"altaVigilancia":False},
"7034":{"nome":"Oxibutinina 5mg cp","controlado":False,"altaVigilancia":False},
"39778":{"nome":"Oxicodona Cloridrato 10mg cp","controlado":True,"altaVigilancia":False},
"2258":{"nome":"Oximetazolina Ad Fr 30ml","controlado":False,"altaVigilancia":False},
"2260":{"nome":"Oximetazolina Ped Fr 20ml","controlado":False,"altaVigilancia":False},
"353":{"nome":"Pancuronio Brometo 2mg/ml 2ml inj.","controlado":False,"altaVigilancia":False},
"38899":{"nome":"Pantoprazol 20mg cap","controlado":False,"altaVigilancia":False},
"4963":{"nome":"Pantoprazol 40mg cp","controlado":False,"altaVigilancia":False},
"11750":{"nome":"Pantoprazol 40mg inj","controlado":False,"altaVigilancia":False},
"37160":{"nome":"Papaina 10% Gel (Tubo C/100G)","controlado":False,"altaVigilancia":False},
"57664":{"nome":"Papaina 5% Gel (Tubo C/100G)","controlado":False,"altaVigilancia":False},
"1436":{"nome":"Papaverina Cloridrato 50mg/ml 2ml inj","controlado":False,"altaVigilancia":False},
"39762":{"nome":"Paracetamol 200mg/ml Gts 15ml","controlado":False,"altaVigilancia":False},
"371":{"nome":"Paracetamol 500mg + Codeína 30mg cp","controlado":True,"altaVigilancia":False},
"373":{"nome":"Paracetamol 500mg + Codeína 7,5mg cp","controlado":True,"altaVigilancia":False},
"351":{"nome":"Paracetamol 500mg cp","controlado":False,"altaVigilancia":False},
"14250":{"nome":"Paracetamol 750mg cp","controlado":False,"altaVigilancia":False},
"7781":{"nome":"Paroxetina Cloridrato 20mg cp","controlado":True,"altaVigilancia":False},
"703":{"nome":"Penicilina G Potássica 5.000.000 Ui inj","controlado":False,"altaVigilancia":False},
"18131":{"nome":"Permetrina 1% Fr 60ml","controlado":False,"altaVigilancia":False},
"288":{"nome":"Petidina Cloridrato (Meperidina) 50mg/ml 2ml inj","controlado":True,"altaVigilancia":False},
"76595":{"nome":"Picossulfato De Sódio 10mg + Óxido De Magnesio 3,5G + Ácido Citrico Anidro 12G Sache","controlado":False,"altaVigilancia":False},
"36994":{"nome":"Picossulfato Sódico 7,5mg/ml Gts 30ml","controlado":False,"altaVigilancia":False},
"7803":{"nome":"Piperacilina 4G + Tazobactam 500mg Ev inj","controlado":False,"altaVigilancia":False},
"6156":{"nome":"Pirimetamina 25mg cp","controlado":False,"altaVigilancia":False},
"4572":{"nome":"Piroxicam Sl 20mg cp","controlado":False,"altaVigilancia":False},
"37163":{"nome":"Plax Colutório Antisséptico 60ml","controlado":False,"altaVigilancia":False},
"96806":{"nome":"Poliaminoácidos 10% 250ml","controlado":False,"altaVigilancia":False},
"67613":{"nome":"Policresuleno 50mg/G Cinchocaina10mg/G pomada (Tubo C/3G)","controlado":False,"altaVigilancia":False},
"99497":{"nome":"Polidocanol 1% 2ml inj","controlado":False,"altaVigilancia":True},
"102309":{"nome":"Polidocanol 3% 2ml inj","controlado":False,"altaVigilancia":True},
"4208":{"nome":"Poliestirenossulfonato De Cálcio 900mg/G Env 30G","controlado":False,"altaVigilancia":False},
"37165":{"nome":"Polimixina B 500 000 Ui inj","controlado":False,"altaVigilancia":False},
"52301":{"nome":"Polivitaminico + Minerais A Z cp","controlado":False,"altaVigilancia":False},
"1610":{"nome":"Potássio Cloreto Liberacao Gradativa 600mg drg","controlado":False,"altaVigilancia":False},
"184":{"nome":"Potássio Cloreto 10% Kcl 10ml inj - Emb. Octogonal","controlado":False,"altaVigilancia":True},
"1604":{"nome":"Potássio Cloreto 6% 60mg/ml Xpe (Frasco C/150ml)","controlado":False,"altaVigilancia":False},
"10151":{"nome":"Pramipexol 0.125mg cp","controlado":True,"altaVigilancia":False},
"31202":{"nome":"Pramipexol 0,25mg cp","controlado":True,"altaVigilancia":False},
"39817":{"nome":"Pramipexol 1mg cp","controlado":True,"altaVigilancia":False},
"2226":{"nome":"Pravastatina 10mg cp","controlado":False,"altaVigilancia":False},
"4751":{"nome":"Prednisolona 1mg/ml Sol Oral 100ml","controlado":False,"altaVigilancia":False},
"2249":{"nome":"Prednisona 20mg cp","controlado":False,"altaVigilancia":False},
"419":{"nome":"Prednisona 5mg cp","controlado":False,"altaVigilancia":False},
"55445":{"nome":"Pregabalina 75mg cap","controlado":True,"altaVigilancia":False},
"77575":{"nome":"Primovist Seringa Preenchida 10ml","controlado":False,"altaVigilancia":False},
"24912":{"nome":"Progesterona Natural Micronizada 200mg cap","controlado":False,"altaVigilancia":False},
"29392":{"nome":"Prometazina Cloridrato Creme 30G","controlado":False,"altaVigilancia":False},
"876":{"nome":"Prometazina Cloridrato 25mg cp","controlado":False,"altaVigilancia":False},
"874":{"nome":"Prometazina Cloridrato 25mg/ml 2ml Im inj","controlado":False,"altaVigilancia":False},
"6051":{"nome":"Propafenona 300mg cp","controlado":False,"altaVigilancia":False},
"1734":{"nome":"Propatilnitrato 10mg cp","controlado":False,"altaVigilancia":False},
"36055":{"nome":"Propofol Pfs 1% 50ml Seringa","controlado":False,"altaVigilancia":False},
"95611":{"nome":"Propofol 1% 50ml inj","controlado":False,"altaVigilancia":False},
"286":{"nome":"Propofol 10mg/ml 20ml inj","controlado":False,"altaVigilancia":False},
"18275":{"nome":"Propranolol 10mg cp","controlado":False,"altaVigilancia":False},
"855":{"nome":"Propranolol 40mg cp","controlado":False,"altaVigilancia":False},
"481":{"nome":"Protamina Cloridrato 10mg/ml 5ml.(Equiv. 5.000Ui) inj","controlado":False,"altaVigilancia":False},
"2198":{"nome":"Psyllium Plantago 5,85G Env.","controlado":False,"altaVigilancia":False},
"39813":{"nome":"Quetiapina Fumarato 100mg cp","controlado":True,"altaVigilancia":False},
"39812":{"nome":"Quetiapina Fumarato 25mg cp","controlado":True,"altaVigilancia":False},
"75806":{"nome":"Racecadotrila 100mg cap","controlado":False,"altaVigilancia":False},
"117425":{"nome":"Raltegravir 100mg Granulado Para Suspensão Oral","controlado":False,"altaVigilancia":False},
"24182":{"nome":"Ramipril 2,5mg cp","controlado":False,"altaVigilancia":False},
"487":{"nome":"Ranitidina 25mg/ml 2ml inj","controlado":False,"altaVigilancia":False},
"14071":{"nome":"Remifentanila 2mg inj","controlado":True,"altaVigilancia":False},
"1564":{"nome":"Retinol 5.000Ui/G + Colecalciferol 900Ui/G + Ox.De Zinco 150mg/G 45G pomada","controlado":False,"altaVigilancia":False},
"73785":{"nome":"Rifampicina 150mg + Isoniazida 75mg + Pirazinamida 400mg + Etambutol 275mg cp (Rhze)","controlado":False,"altaVigilancia":False},
"11610":{"nome":"Rifampicina 300mg cap","controlado":False,"altaVigilancia":False},
"9360":{"nome":"Risperidona 1mg cp","controlado":True,"altaVigilancia":False},
"3273":{"nome":"Risperidona 2mg cp","controlado":True,"altaVigilancia":False},
"59447":{"nome":"Rivaroxabana 15mg cp","controlado":False,"altaVigilancia":False},
"58538":{"nome":"Rivaroxabana 20mg cp","controlado":False,"altaVigilancia":False},
"37134":{"nome":"Rivastigmina 1,5mg cap.","controlado":True,"altaVigilancia":False},
"6392":{"nome":"Rocurônio Brometo10mg/ml 5ml inj","controlado":False,"altaVigilancia":False},
"9331":{"nome":"Ropivacaína 10mg/ml 20ml inj","controlado":False,"altaVigilancia":False},
"9330":{"nome":"Ropivacaína 2mg/ml 20ml inj","controlado":False,"altaVigilancia":False},
"19961":{"nome":"Ropivacaína 7,5mg/ml 20ml inj","controlado":False,"altaVigilancia":False},
"98470":{"nome":"Rosuvastatina 10mg cp","controlado":False,"altaVigilancia":False},
"797":{"nome":"Saccharomyces Boulardii 100mg cap","controlado":False,"altaVigilancia":False},
"129413":{"nome":"Sacubitril Valsartana Sódica 50mg cp Rev","controlado":False,"altaVigilancia":False},
"2314":{"nome":"Salbutamol 0,4mg/ml Sol Oral 120ml","controlado":False,"altaVigilancia":False},
"38952":{"nome":"Salbutamol 0,5mg/ml 1ml inj","controlado":False,"altaVigilancia":False},
"5870":{"nome":"Salbutamol 100mcg/Dose Spray Fr 200 Doses","controlado":False,"altaVigilancia":False},
"8832":{"nome":"Salbutamol 5mg/ml 10ml Sol. P/ Nebulizacao","controlado":False,"altaVigilancia":False},
"39140":{"nome":"Salmeterol Xinafoato 25mcg + Fluticasona 250mcg Spray","controlado":False,"altaVigilancia":False},
"10810":{"nome":"Salmeterol Xinafoato 50mcg + Fluticasona 250mcg Frasco (Diskus)","controlado":False,"altaVigilancia":False},
"21001":{"nome":"Sene + Cassia + Tamarindus + Coriandrum Sativum + Alcacuz Geleia (Frasco C/ 150G)","controlado":False,"altaVigilancia":False},
"37198":{"nome":"Sertralina Cloridrato 25mg cp","controlado":True,"altaVigilancia":False},
"4319":{"nome":"Sertralina Cloridrato 50mg cp","controlado":True,"altaVigilancia":False},
"1515":{"nome":"Sevoflurano 250ml","controlado":False,"altaVigilancia":True},
"40154":{"nome":"Sildenafil 25mg cp.","controlado":False,"altaVigilancia":False},
"318":{"nome":"Simeticona 40mg cp","controlado":False,"altaVigilancia":False},
"320":{"nome":"Simeticona 75mg/ml Gts 10ml","controlado":False,"altaVigilancia":False},
"8306":{"nome":"Sinvastatina 20mg cp","controlado":False,"altaVigilancia":False},
"36767":{"nome":"Sinvastatina 40mg cp","controlado":False,"altaVigilancia":False},
"37186":{"nome":"Solução Cardioplegica 10ml inj","controlado":False,"altaVigilancia":True},
"2269":{"nome":"Solução De Cloreto De Sódio 0,9% (Contém Benzalcônio) – Solução Nasal Fr 30ml","controlado":False,"altaVigilancia":False},
"3061":{"nome":"Solução Enema Glicerinado 12% 500ml Frasco Solução Fisiologico 0,9% 1000ml inj Bolsa Baxter (Cardíaca)","controlado":False,"altaVigilancia":False},
"74161":{"nome":"Solução Heparina 100 Ui/ml 5ml Seringa","controlado":False,"altaVigilancia":False},
"95505":{"nome":"Solução Reposicao Hidroeletrolitica ( Na 140/ K 5/mg 3/ Cl 98/ Acetato 27/ Gluconato 23/ Meq/L)500ml","controlado":False,"altaVigilancia":False},
"72586":{"nome":"Solução Salina 0,9% 10ml Seringa","controlado":False,"altaVigilancia":False},
"72584":{"nome":"Solução Salina 0,9% 3ml Seringa","controlado":False,"altaVigilancia":False},
"39834":{"nome":"Sorbitol + Laurilsulfato De Sódio 6,5G","controlado":False,"altaVigilancia":False},
"1563":{"nome":"Stomahesive (Pasta)","controlado":False,"altaVigilancia":False},
"1035":{"nome":"Stomahesive (Pó Protetor)","controlado":False,"altaVigilancia":False},
"36145":{"nome":"Sucralfato 1000mg cp","controlado":False,"altaVigilancia":False},
"1519":{"nome":"Sufentanila 5mcg/ml inj 2M","controlado":True,"altaVigilancia":False},
"1517":{"nome":"Sufentanila 50mcg/ml inj 1ml","controlado":True,"altaVigilancia":False},
"59502":{"nome":"Sugamadex 100mg/ml 2ml inj","controlado":False,"altaVigilancia":False},
"13520":{"nome":"Sulfadiazina De Prata 1% Creme 30G","controlado":False,"altaVigilancia":False},
"36537":{"nome":"Sulfametoxazol 400mg + Trimetoprima 80mg cp","controlado":False,"altaVigilancia":False},
"594":{"nome":"Sulfametoxazol 400mg + Trimetoprima 80mg 5ml inj","controlado":False,"altaVigilancia":False},
"39680":{"nome":"Sulfametoxazol 400mg+ Trimetropina 80mg/5ml -100ml Fr.","controlado":False,"altaVigilancia":False},
"617":{"nome":"Sulfametoxazol 800mg + Trimetoprima 160mg cp","controlado":False,"altaVigilancia":False},
"182":{"nome":"Sulfato De Magnesio 50% 10ml inj","controlado":False,"altaVigilancia":True},
"891":{"nome":"Sulfato Ferroso 250mg drg","controlado":False,"altaVigilancia":False},
"39820":{"nome":"Sulpirida 50mg cp","controlado":True,"altaVigilancia":False},
"36629":{"nome":"Sumatriptano Succinato 50mg cp.","controlado":False,"altaVigilancia":False},
"304":{"nome":"Sumatriptano Succinato 6mg/0,5ml Seringa","controlado":False,"altaVigilancia":False},
"2204":{"nome":"Supositório De Glicerina Ad","controlado":False,"altaVigilancia":False},
"25312":{"nome":"Surfactante (Fosfolipideos) 80mg/ml 3ml inj","controlado":False,"altaVigilancia":False},
"5740":{"nome":"Suxametonio Cloreto 100mg inj","controlado":False,"altaVigilancia":True},
"36931":{"nome":"Tamoxifeno 20mg cp","controlado":False,"altaVigilancia":False},
"9011":{"nome":"Tansulosina Cloridrato 0,4mg cap","controlado":False,"altaVigilancia":False},
"55797":{"nome":"Tcm Loção Oleosa Fr 100ml","controlado":False,"altaVigilancia":False},
"55796":{"nome":"Tcm Loção Oleosa Fr 20ml","controlado":False,"altaVigilancia":False},
"57990":{"nome":"Telmisartana 40mg cp","controlado":False,"altaVigilancia":False},
"8801":{"nome":"Tenoxicam 20mg cp","controlado":False,"altaVigilancia":False},
"2178":{"nome":"Tenoxicam 20mg inj","controlado":False,"altaVigilancia":False},
"39723":{"nome":"Tenoxicam 40mg inj","controlado":False,"altaVigilancia":False},
"2332":{"nome":"Terbutalino Sulfato 0,5mg/ml 1ml inj","controlado":False,"altaVigilancia":False},
"39890":{"nome":"Terlipressina Acetato 1mg inj","controlado":False,"altaVigilancia":False},
"108633":{"nome":"Teste Rapido Covid 19","controlado":False,"altaVigilancia":True},
"14241":{"nome":"Tetraciclina + Anfotericina B Creme Vaginal 45G","controlado":False,"altaVigilancia":False},
"53328":{"nome":"Tiamina + Piridoxina + Cianocobalamina 2500 Ui/ml 2ml inj","controlado":False,"altaVigilancia":False},
"2140":{"nome":"Tiamina 300mg cp","controlado":False,"altaVigilancia":False},
"98537":{"nome":"Tiamina Cloridrato 100mg/ml 1ml inj Im/Ev","controlado":False,"altaVigilancia":False},
"2150":{"nome":"Tiamina100mg+Piridoxina100mg+Cianocobalamina 5mg","controlado":False,"altaVigilancia":False},
"61935":{"nome":"Ticagrelor 90mg cp","controlado":False,"altaVigilancia":False},
"37204":{"nome":"Tigeciclina 50mg inj","controlado":False,"altaVigilancia":False},
"25852":{"nome":"Timolol Maleato 0,5% Colírio 5ml","controlado":False,"altaVigilancia":False},
"56853":{"nome":"Tiotropio Brometo 2,5mcg Respimat","controlado":False,"altaVigilancia":False},
"13241":{"nome":"Tirofiban 50ml (0,25mg/ml) inj.","controlado":False,"altaVigilancia":False},
"105946":{"nome":"Tisseel Lyo 4ml","controlado":False,"altaVigilancia":False},
"37184":{"nome":"Tizanidina 2mg cp.","controlado":True,"altaVigilancia":False},
"10863":{"nome":"Tobramicina 0,3% + Dexametasona 0,1% Colírio (Frasco C/5ml)","controlado":False,"altaVigilancia":False},
"1459":{"nome":"Tobramicina 0,3% Colírio 5ml","controlado":False,"altaVigilancia":False},
"10360":{"nome":"Tobramicina 0,3% pomada Oftálmica 3,5G","controlado":False,"altaVigilancia":False},
"40849":{"nome":"Topiramato 50mg cp","controlado":True,"altaVigilancia":False},
"26802":{"nome":"Toxina Botulinica Tipo A 100Ui inj","controlado":False,"altaVigilancia":False},
"36045":{"nome":"Tramadol Cloridrato 100mg inj","controlado":True,"altaVigilancia":False},
"39777":{"nome":"Tramadol Cloridrato 100mg cp","controlado":True,"altaVigilancia":False},
"4073":{"nome":"Tramadol Cloridrato 50mg inj","controlado":True,"altaVigilancia":False},
"1652":{"nome":"Tramadol Cloridrato 50mg cap","controlado":True,"altaVigilancia":False},
"39811":{"nome":"Trazodona Cloridrato 50mg cp","controlado":True,"altaVigilancia":False},
"1702":{"nome":"Triancinolona + Neomicina + Gramicidina + Nistatina Creme 30G","controlado":False,"altaVigilancia":False},
"81373":{"nome":"Triancinolona Acetonida 20mg/ml 5ml inj","controlado":False,"altaVigilancia":False},
"7961":{"nome":"Triancinolona Acetonido Orabase 10G","controlado":False,"altaVigilancia":False},
"53606":{"nome":"Trimetazidina 35mg cp","controlado":False,"altaVigilancia":False},
"39818":{"nome":"Trometamina Cetorolaco Sl 10mg cp","controlado":False,"altaVigilancia":False},
"39819":{"nome":"Trometamina Cetorolaco 30mg/ml 1ml inj","controlado":False,"altaVigilancia":False},
"27352":{"nome":"Valsartana Potassica 80mg cp","controlado":False,"altaVigilancia":False},
"753":{"nome":"Vancomicina Cloridrato 500mg inj","controlado":False,"altaVigilancia":False},
"97700":{"nome":"Varfarina 2,5mg cp","controlado":False,"altaVigilancia":True},
"772":{"nome":"Varfarina 5mg cp","controlado":False,"altaVigilancia":True},
"37207":{"nome":"Vaselina pomada 30G","controlado":False,"altaVigilancia":False},
"40062":{"nome":"Vasopressina 20 U/ml inj 1ml","controlado":False,"altaVigilancia":False},
"11265":{"nome":"Venlafaxina Xr 75mg cap","controlado":True,"altaVigilancia":False},
"37045":{"nome":"Venlafaxina 37,5mg cap","controlado":True,"altaVigilancia":False},
"568":{"nome":"Verapamil Cloridrato 80mg cp","controlado":False,"altaVigilancia":False},
"54179":{"nome":"Visipaque - Iodixanol 550mg/ml (270mg I/ml) 50ml","controlado":False,"altaVigilancia":False},
"1473":{"nome":"Vitamina A + Aminoácidos Cloranfenicol pomada Oftalmologica (Tubo C/3,5G)","controlado":False,"altaVigilancia":False},
"132467":{"nome":"Vitamina A (0,2mg/ml) + Vitamina D (0,01mg/ml) + Ferro (12mg/ml) - Gotas/Frasco 30ml","controlado":False,"altaVigilancia":False},
"68512":{"nome":"Vitamina C (Ácido Ascorbico) 200mg/ml 20ml Gts","controlado":False,"altaVigilancia":False},
"104334":{"nome":"Vitamina D (250Ui/Gota)/Vitamina A (1250Ui/Gota) (Frasco C/10ml)","controlado":False,"altaVigilancia":False},
"110542":{"nome":"Vitamina E","controlado":False,"altaVigilancia":False},
"128136":{"nome":"Zidovudina 10mg/ml Sol. Oral","controlado":False,"altaVigilancia":False},
"108703":{"nome":"Zinco Sulfato 17,60mg/ml (4mg/ml Zn Elementar) Sol. 100ml","controlado":False,"altaVigilancia":False},
"38411":{"nome":"Zolpidem 10mg cp","controlado":True,"altaVigilancia":False},
}




# Criação de dicionário para mapear IDs para nomes completos
# mapa_medicamentos = {}

# for med in listaMedicamentos:
#     partes = med.split()
#     if len(partes) >= 2:
#         id_medicamento = partes[0]
#         nome_medicamento = ' '.join(partes[1:])
#         mapa_medicamentos[id_medicamento] = nome_medicamento

# # Lista com nomes dos medicamentos
# nome_medicamentos = list(mapa_medicamentos.values())
# print(nome_medicamentos)

# nome_selecionado = 'Zompidem 10mg cp'
# id_associado = None

# # Procurar o ID correspondente ao nome
# for id_medicamento, nome_medicamento in mapa_medicamentos.items():
#     if nome_medicamento == nome_selecionado:
#         id_associado = id_medicamento
#         break

# if id_associado is not None:
#     print(f"O ID associado ao nome {nome_selecionado} é: {id_associado}")
# else:
#     print(f"Nome {nome_selecionado} não encontrado.")